baseURL = "/"
title = "Blog"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2018 - 2019 HeisebergV -- All rights reserved."

# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"
# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true

[params]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given

[author]
  name = "heisenberg"
  github = "heisenbergV"
  email = "zuojxin@hotmail.com"
  twitter = "Vdemoot"